"""add wx_observations table and wx_prob column

Revision ID: 5cd46cb0df3b
Revises: 317867a84a41
Create Date: 2026-04-18 00:11:07.905539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5cd46cb0df3b'
down_revision: Union[str, None] = '317867a84a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wx_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_icao', sa.String(), nullable=False),
    sa.Column('valid_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_time_local', sa.String(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('dewpoint_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_gust_ms', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.Integer(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('pressure_trend', sa.String(), nullable=True),
    sa.Column('precip_1h_mm', sa.Float(), nullable=True),
    sa.Column('precip_6h_mm', sa.Float(), nullable=True),
    sa.Column('precip_24h_mm', sa.Float(), nullable=True),
    sa.Column('snow_1h_mm', sa.Float(), nullable=True),
    sa.Column('snow_24h_mm', sa.Float(), nullable=True),
    sa.Column('temp_max_since_7am_c', sa.Float(), nullable=True),
    sa.Column('temp_max_24h_c', sa.Float(), nullable=True),
    sa.Column('temp_min_24h_c', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Integer(), nullable=True),
    sa.Column('visibility_km', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_icao', 'valid_time_local', name='uq_wx_station_time')
    )
    op.create_index('ix_wx_station_valid', 'wx_observations', ['station_icao', 'valid_time_utc'], unique=False)
    op.add_column('signals', sa.Column('wx_prob', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'wx_prob')
    op.drop_index('ix_wx_station_valid', table_name='wx_observations')
    op.drop_table('wx_observations')
    # ### end Alembic commands ###
